# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9ae388c0e983158b003f0b95d9698f534d1203bc9afcc0d1114dd2bf2e4586aacff7c75ccc8b07bb8f9626f720edc7f89580381ca653ea0e96907ab4fdce555b

test:
  secret_key_base: 4d8c9054b316eaa2116a6da9fb022ebd7170f71c31b5d28300bc20800aa19e615196dad0b96bbb42204f381a7dca08477ab95ca5d88fdd750c6d9e0047632ec6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
